// ESLint flat config — authored in TypeScript (loaded via jiti), per the
// project's TypeScript-only-source rule.
//
// The Nuxt-aware base config is generated by @nuxt/eslint into
// ./.nuxt/eslint.config.mjs (a build artifact regenerated by `nuxt prepare`,
// not committed source). We extend it with project-specific rules here.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Single-file components for this app are intentionally single-word
    // (e.g. filter components live under components/filters/).
    'vue/multi-word-component-names': 'off',
  },
})
